[package]
name = "histo-log"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asciigraph = "^0.6.0"
# fix versions for older rust
clap = { version = "=4.0.32", features = ["derive"] }
clap_lex = { version = "=0.3.0" }
regex = { version = "=1.9.6" }
rust_decimal = "1.33.1"
