name: histo-log
version: git
summary: CLI tools for generating histograms from log files
description: |
  histo-log is a command line program for parsing log files and
  generating histograms from the contents.

  It's mostly a test-bed for learning rust for me.

  This is also an experiment in snap packaging for rust since debian
  rust packaging seems beyond my ability to wrestle the dependencies.

base: core20
confinement: classic

parts:
  histo-log:
    plugin: rust
    source: .

apps:
  histo-log:
    command: bin/histo-log
