name: Snap build

on:
  push:
    branches:
      - main
      - '**/*github*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
