name: Test builds

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{matrix.rust}} on ${{matrix.os}} with ${{matrix.feature_flag}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust:
          - 1.75.0
          - 1.63.0
          - stable
        feature_flag:
          - ~
          - "--no-default-features"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Reset toolchain
        run: rm -f rust-toolchain.toml
        shell: bash

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: clippy

      - name: Build
        run: cargo build ${{matrix.feature_flag}}

      - name: Unit-test
        run: cargo test ${{matrix.feature_flag}}

      - name: Analyze
        run: cargo clippy ${{matrix.feature_flag}} -- --deny warnings

      - name: Install test deps
        run: sudo apt install -y bats
        if: runner.os == 'Linux'

      - name: Run bats test
        run: bats ./tests
        if: runner.os == 'Linux'
